### ISSUE TITLE
How to deploy this demo on AKS

### ISSUE THREAD

**Issue by vrushaltalegaonkar** [Sitecore/Sitecore.Demo.Edge#298]
I can see there are some helm charts provided in the documentation.
But what are the detailed steps to get this site on AKS and what type or precautions we will need to take while doing this activity ?

**Comment by jeanfrancoislarente** [comment]
This is an extremely old issue that has gone unanswered, apologies. Despite that it may be obsolete, I will still respond for historical purpose.

Although our team deploys to AKS and the container assets are tested in AKS, we do not directly support attempts to deploy to AKS and that primarily due to a time and resource issue.

Those wanting to deploy to AKS should be able to review the various docker-compose files to determine which environment variables are required and translate those into kubernetes config or helm charts.
